parameters:
#    nf_platform.example.class: NF\PlatformBundle\Example

services:
#    nf_platform.example:
#        class: %oc_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]