<?php

namespace NF\PlatformBundle\Entity;

/**
 * ExcelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcelRepository extends \Doctrine\ORM\EntityRepository
{
}
