<?php

namespace NF\PlatformBundle\Entity;

/**
 * MontantSousCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantSousCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
