<?php

namespace NF\PlatformBundle\Entity;

/**
 * MontantTotalJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantTotalJourRepository extends \Doctrine\ORM\EntityRepository
{
}
