<?php

namespace NF\PlatformBundle\Entity;

/**
 * MontantJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantJourRepository extends \Doctrine\ORM\EntityRepository
{
}
