<?php

namespace NF\PlatformBundle\Entity;

/**
 * MontantSemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantSemaineRepository extends \Doctrine\ORM\EntityRepository
{
}
