<?php

namespace Proxies\__CG__\NF\PlatformBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activities extends \NF\PlatformBundle\Entity\Activities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'id', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'date', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'numSemaine', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'montant', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'coment', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'user', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'sousCategories');
        }

        return array('__isInitialized__', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'id', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'date', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'numSemaine', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'montant', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'coment', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'user', '' . "\0" . 'NF\\PlatformBundle\\Entity\\Activities' . "\0" . 'sousCategories');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSemaine($numSemaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSemaine', array($numSemaine));

        return parent::setNumSemaine($numSemaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSemaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSemaine', array());

        return parent::getNumSemaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', array($montant));

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', array());

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setComent($coment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComent', array($coment));

        return parent::setComent($coment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComent', array());

        return parent::getComent();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\NF\PlatformBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousCategories(\NF\PlatformBundle\Entity\SousCategories $sousCategories = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousCategories', array($sousCategories));

        return parent::setSousCategories($sousCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousCategories', array());

        return parent::getSousCategories();
    }

}
